version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_DATABASE=wsdb
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=root
      - MARIADB_PASSWORD=password 
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
